### PR TITLE
Python3 conversion & small bugfix

### PR DESCRIPTION
**Pull request by rimas-kudelis**

### CODE REVIEW

**Review by ndemou — APPROVED** [review]
Thanks!

**Review by ndemou — APPROVED** [review]
Thanks again :-)

**Comment by rimas-kudelis** [comment]
Hehe, I see you updated the readme, but left the original Python versions in it. :)

**Comment by ndemou** [comment]
Fixed! Thanks again for the contribution Rimas!

**Comment by rimas-kudelis** [comment]
No problem. :) This script came really handy for me. :)

**Pull request merged**
